FROM maven:3.8.5-openjdk-17 

WORKDIR /app
COPY . .


# CMD per avviare l'applicazione Spring Boot (opzionale, dipende dalla tua configurazione)
CMD ["java", "-jar", "target/eureka-service-0.0.1-SNAPSHOT.jar"]
