version: '2'
services:


  eureka-server:
    container_name: eureka-server
    build:
      context: eureka-service
      dockerfile: Dockerfile
    image: eureka-server:latest
    ports:
      - 8761:8761
    networks:
      - spring-cloud-network

  security-server:
    container_name: security-server
    build:
      context: security-service
      dockerfile: Dockerfile
    image: security-server:latest
    ports:
      - 8081:8081
    networks:
      - spring-cloud-network

  mysql-db:
    image: mysql:latest
    container_name: mysql-db
    #ports:
     # - 3307:3306
    environment: 
      MYSQL_DATABASE: mydatabase
      MYSQL_ROOT_USER: root
      MYSQL_ROOT_PASSWORD: rootpassword
    # MYSQL_USER: root
#      MYSQL_PASSWORD: userpassword
    volumes:
      - mysql_data:/var/lib/mysql
    networks:
      - spring-cloud-network

networks:
  spring-cloud-network:
    driver: bridge

volumes:
  mysql_data:
